#!/bin/bash
# Quick Test Script for Icon Card System
# 
# This script helps you test the Icon Card system quickly
#
# Usage: Run this file or follow the manual steps below

echo "🎴 ICON KART SİSTEMİ - HIZLI TEST"
echo "=================================="
echo ""
echo "✅ Oluşturulan Dosyalar:"
echo "  1. lib/widgets/icon_card.dart (Ana widget)"
echo "  2. lib/data/card_types.dart (Kart türleri)"
echo "  3. lib/widgets/create_card_dialog.dart (Dialog)"
echo "  4. lib/screens/card_types_example.dart (Örnek sayfa)"
echo "  5. lib/screens/icon_card_showcase.dart (Showcase)"
echo ""
echo "📚 Belgeler:"
echo "  - QUICK_START.md (Hızlı başlangıç)"
echo "  - ICON_CARD_USAGE.md (Detaylı kilavuz)"
echo "  - INTEGRATION_GUIDE.dart (Entegrasyon örnekleri)"
echo ""
echo "🚀 TEST ETMEK İÇİN:"
echo "  1. Flutter çalışıyor mu kontrol et:"
echo "     flutter doctor"
echo ""
echo "  2. Paketleri yükle:"
echo "     flutter pub get"
echo ""
echo "  3. Uygulamayı çalıştır:"
echo "     flutter run -d windows"
echo ""
echo "  4. Örneği main.dart'da açmak için:"
echo "     - main.dart'ı aç"
echo "     - card_types_example.dart'ı import et"
echo "     - MyApp'in home: CardTypesExample() yap"
echo ""
echo "💡 HIZLI BAŞLANGIÇ:"
echo "  import 'widgets/icon_card.dart';"
echo "  import 'data/card_types.dart';'"
echo ""
echo "  IconCard("
echo "    icon: Icons.diamond,"
echo "    title: 'KARO',"
echo "    iconColor: Colors.blueAccent,"
echo "  )"
echo ""
echo "✨ Yapıldı! Şimdi test et → flutter run -d windows"
